runtime: python27
api_version: 1
threadsafe: yes

handlers:
# FAVICON
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

# RESUME
- url: /resume\.pdf
  static_files: static/Hunter Larco Resume.pdf
  upload: static/Hunter Larco Resume\.pdf

# STATIC DIRECTORIES
- url: /images
  static_dir: images
- url: /resources
  static_dir: resources
- url: /projects
  static_dir: projects

# PROJECT SHORTCUTS
- url: /nybble/?
  static_files: projects/nybble/main.html
  upload: projects/nybble/main\.html

# MAIN SCRIPT
- url: .*
  script: app.app

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.2"
