application: hunterlarcopersonal
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /resume\.pdf
  static_files: static/Hunter Larco Resume.pdf
  upload: static/Hunter Larco Resume\.pdf

- url: /images
  static_dir: images
- url: /resources
  static_dir: resources

- url: .*
  script: app.app

libraries:
- name: webapp2
  version: "2.5.1"