application: hunterlarcopersonal
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# APP STATS
- url: /frontend/_/stats(/.*)?
  script: google.appengine.ext.appstats.ui.app
  login: admin

# FAVICON
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

# STATIC HANDLER
- url: /static
  static_dir: static

# API SCRIPT
- url: .*
  script: app.app

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- appstats: on
- remote_api: on